/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignInImport } from './routes/sign-in'
import { Route as LayoutImport } from './routes/_layout'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const LayoutTeamLazyImport = createFileRoute('/_layout/team')()
const LayoutTaskLazyImport = createFileRoute('/_layout/task')()
const LayoutProjectLazyImport = createFileRoute('/_layout/project')()
const LayoutDashboardLazyImport = createFileRoute('/_layout/dashboard')()

// Create/Update Routes

const SignInRoute = SignInImport.update({
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutTeamLazyRoute = LayoutTeamLazyImport.update({
  path: '/team',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() => import('./routes/_layout/team.lazy').then((d) => d.Route))

const LayoutTaskLazyRoute = LayoutTaskLazyImport.update({
  path: '/task',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() => import('./routes/_layout/task.lazy').then((d) => d.Route))

const LayoutProjectLazyRoute = LayoutProjectLazyImport.update({
  path: '/project',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() =>
  import('./routes/_layout/project.lazy').then((d) => d.Route),
)

const LayoutDashboardLazyRoute = LayoutDashboardLazyImport.update({
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() =>
  import('./routes/_layout/dashboard.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/sign-in': {
      preLoaderRoute: typeof SignInImport
      parentRoute: typeof rootRoute
    }
    '/_layout/dashboard': {
      preLoaderRoute: typeof LayoutDashboardLazyImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/project': {
      preLoaderRoute: typeof LayoutProjectLazyImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/task': {
      preLoaderRoute: typeof LayoutTaskLazyImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/team': {
      preLoaderRoute: typeof LayoutTeamLazyImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  LayoutRoute.addChildren([
    LayoutDashboardLazyRoute,
    LayoutProjectLazyRoute,
    LayoutTaskLazyRoute,
    LayoutTeamLazyRoute,
  ]),
  SignInRoute,
])

/* prettier-ignore-end */
